"""empty message

Revision ID: 11fe7a962231
Revises: d610f5508497
Create Date: 2025-11-24 19:39:47.588065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fe7a962231'
down_revision = 'd610f5508497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formacao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'formacao', ['formacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('formacao_id')

    # ### end Alembic commands ###
